### Health check

GET http://localhost:3000/health

### Register check

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "firstname" : "Skander",
  "lastname" : "Saafi",
  "email" : "tes@gmail.com",
  "password" : "12345678",
  "username" : "skander"
}


### Login Check
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email" : "tes@gmail.com",
  "password" : "12345678"
}

### Profile Public Check
GET http://localhost:3000/api/users/skander
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhM2Q2MTE0YTRhODhiOWE2OTFjZTAzNyIsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoic2thbmRlciIsImlhdCI6MTc4MjQyMTA1OSwiZXhwIjoxNzg1MDEzMDU5fQ.lJZ9m6jDraIuU5NvfaSKzYDcQyk-abDD6sBoET2mTUg

### Profile Private Check
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhM2Q2MTE0YTRhODhiOWE2OTFjZTAzNyIsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoic2thbmRlciIsImlhdCI6MTc4MjQyMTA1OSwiZXhwIjoxNzg1MDEzMDU5fQ.lJZ9m6jDraIuU5NvfaSKzYDcQyk-abDD6sBoET2mTUg

### Upload avatar
POST http://localhost:3000/api/users/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhM2Q2MTE0YTRhODhiOWE2OTFjZTAzNyIsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoic2thbmRlciIsImlhdCI6MTc4MjQyMTA1OSwiZXhwIjoxNzg1MDEzMDU5fQ.lJZ9m6jDraIuU5NvfaSKzYDcQyk-abDD6sBoET2mTUg
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/png

avatar.png
------boundary--

### Update Profile
PUT http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhM2Q2MTE0YTRhODhiOWE2OTFjZTAzNyIsImVtYWlsIjoidGVzQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoic2thbmRlciIsImlhdCI6MTc4MjQyMTA1OSwiZXhwIjoxNzg1MDEzMDU5fQ.lJZ9m6jDraIuU5NvfaSKzYDcQyk-abDD6sBoET2mTUg
Content-Type: application/json

{
  "bio" : "I am Skander and I love web dev",
  "username" : "Skandi"
}